# Generated by Django 4.2.1 on 2024-04-10 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_alter_productcart_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcart',
            options={'ordering': ('id',), 'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзины'},
        ),
    ]
