# Generated by Django 4.2.1 on 2024-02-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_genre_movie_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
