# Generated by Django 4.2.1 on 2024-03-26 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_alter_session_hall'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='session',
        ),
        migrations.AddField(
            model_name='session',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='cinema.movie', verbose_name='Информация о фильме'),
        ),
    ]
