# Generated by Django 4.2.1 on 2024-02-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_alter_genre_name_alter_genre_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='starring',
            field=models.CharField(max_length=500, verbose_name='В главных ролях'),
        ),
    ]
