# Generated by Django 4.2.1 on 2024-02-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0005_alter_movie_starring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='starring',
            field=models.TextField(max_length=500, verbose_name='В главных ролях'),
        ),
    ]
