# Generated by Django 4.2.1 on 2024-02-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0006_alter_movie_description_alter_movie_starring'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата сеанса')),
                ('time', models.TimeField(verbose_name='Время сеанса')),
                ('hall_number', models.IntegerField(verbose_name='Номер зала')),
            ],
            options={
                'verbose_name': 'Сеанс',
                'verbose_name_plural': 'Сеансы',
            },
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(related_name='genres', to='cinema.genre', verbose_name='Жанр'),
        ),
        migrations.AddField(
            model_name='movie',
            name='sessions',
            field=models.ManyToManyField(related_name='session', to='cinema.filminfo', verbose_name='Информация о фильме'),
        ),
    ]
