# Generated by Django 4.2.1 on 2024-02-12 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0007_filminfo_alter_movie_genre_movie_sessions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FilmInfo',
            new_name='Session',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='sessions',
            new_name='session',
        ),
    ]
