# Generated by Django 4.2.1 on 2024-02-13 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0008_rename_filminfo_session_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер зала')),
                ('places', models.IntegerField(verbose_name='Количество обычных мест')),
                ('vip_places', models.IntegerField(verbose_name='Количество премиум мест')),
                ('price_default_places', models.IntegerField(verbose_name='Стоимость обычных мест')),
                ('price_vip_places', models.IntegerField(verbose_name='Стоимость премиум мест')),
            ],
            options={
                'verbose_name': 'Зал',
                'verbose_name_plural': 'Залы',
            },
        ),
        migrations.RemoveField(
            model_name='session',
            name='hall_number',
        ),
        migrations.AddField(
            model_name='session',
            name='hall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.hall', verbose_name='Номер зала'),
        ),
    ]
