# Generated by Django 4.2.1 on 2024-02-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0009_hall_remove_session_hall_number_session_hall'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('Скоро в прокате', 'Скоро в прокате'), ('Опубликован', 'Опубликован'), ('Архив', 'Архив')], default='Скоро в прокате', max_length=20, verbose_name='Статус фильма'),
        ),
    ]
