# Generated by Django 4.1.13 on 2024-04-14 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderticketitem',
            options={'verbose_name': 'Проданный билет', 'verbose_name_plural': 'Проданные билеты'},
        ),
    ]
